on:
  pull_request:
    # only check if a file is changed within the project_euler directory and related files
    paths:
      - 'project_euler/**'
      - '.github/workflows/project_euler.yml'
      - 'scripts/validate_solutions.py'

name: 'Project Euler'

jobs:
  project-euler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install pytest and pytest-cov
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest pytest-cov
      - run: pytest --doctest-modules --cov-report=term-missing:skip-covered --cov=project_euler/ project_euler/
  validate-solutions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest
      - run: pytest scripts/validate_solutions.py
